nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.nodes.ZarrDatasetNodeBuilder
      dataset: /path/to/dataset.zarr
    attributes:
      weights:
        _target_: anemoi.graphs.nodes.attributes.AreaWeights # options: AreaWeights, UniformWeights
        norm: unit-max
  hidden: ...
